//
//  PoetFileTest.swift
//  SwiftPoetTests
//
//  Created by Eugene Kazaev on 24/04/2018.
//  Copyright © 2018 Gilt Groupe. All rights reserved.
//

import XCTest
import SwiftPoet

class PoetFileTest: XCTestCase {
    
    override func setUp() {
        super.setUp()
        // Put setup code here. This method is called before the invocation of each test method in the class.
    }
    
    override func tearDown() {
        // Put teardown code here. This method is called after the invocation of each test method in the class.
        super.tearDown()
    }
    
    func testHeaderWithNoDate() {
        let cb = ClassSpec.builder(for: "TopLevelClass")
        
        let classSpec = cb.build()
        
        let poetFile = PoetFile(spec: classSpec, generatorInfo: nil, addGenerationDate: false)
        let result = """
        //
        //  TopLevelClass.swift
        //
        //  Contains:
        //  class TopLevelClass
        //
        //  Generated by SwiftPoet
        //

        class TopLevelClass {
        
        }

        """

        XCTAssertEqual(result, poetFile.fileContents)
    }

    func testImports() {
        let cb = ClassSpec.builder(for: "ClassB")
        cb.add(import: "UIKit")
        cb.add(import: "Foundation")
        cb.add(import: "DependencyB")
        cb.add(import: "DependencyA")

        let ca = ClassSpec.builder(for: "ClassA")
        ca.add(import: "UIKit")
        ca.add(import: "Foundation")
        ca.add(import: "DependencyD")
        ca.add(import: "DependencyC")

        let classBSpec = cb.build()
        let classASpec = ca.build()

        let poetFile = PoetFile(list: [classBSpec, classASpec], generatorInfo: nil, addGenerationDate: false)
        let result = """
        //
        //  ClassB.swift
        //
        //  Contains:
        //  class ClassB
        //  class ClassA
        //
        //  Generated by SwiftPoet
        //

        import DependencyA
        import DependencyB
        import DependencyC
        import DependencyD
        import Foundation
        import UIKit

        class ClassB {

        }

        class ClassA {

        }

        """

        XCTAssertEqual(result, poetFile.fileContents)
    }
}
